// next imports
import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'

// component imports

// helper imports

// for props we are passing into components
type Props = {}

// NextPage is a typing for pages in ts next
const Home: NextPage = ({} : Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        {/* change for deployment */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}

export default Home

// this allows us to query the backend on load to lessen the strain on loading time. (bit that broke me over the weekend.)
// export const getStaticProps: GetStaticProps<Props> = async () => {
  // return {
  //   props: {

  //   },
  //   revalidate: // when do we want it to check for an update
  // }

// }