// next imports
import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'

// component imports
import TestPage from '../components/testPage'

// helper imports
import type { ExpandedExample } from '../typings' // this is a custom type created in typings that is set to match test class instance

// for props we are passing into components
type Props = {}

// an object created with a typescript type. 
let propTest : ExpandedExample = {
  id: 'car',
  createdAt: 'noon',
  title: 'john',
  complete: false,
  
}

// NextPage is a typing for pages in ts next deleting it cause its not needed currently
// pass prop down here
const Home = ({} : Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        {/* change for deployment */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Parent Page</p>
      
      {/* testPage */}
      <TestPage test={propTest} />

      

    </div>
  )
}

export default Home

// this allows us to query the backend on load to lessen the strain on loading time. (bit that broke me over the weekend.)
// export const getStaticProps: GetStaticProps<Props> = async () => {
  // return {
  //   props: {

  //   },
  //   revalidate: // when do we want it to check for an update
  // }

// }